// Database types matching the schema
// Re-generate with: npm run db:generate

export interface User {
  id: string
  telegram_id: number
  telegram_username: string | null
  instagram_handle: string | null
  credits: number
  plan: 'free' | 'spark' | 'flame'
  plan_expires_at: string | null
  searches_this_month: number
  unlocks_this_month: number
  month_reset_at: string
  taipei_area: boolean
  created_at: string
  updated_at: string
}

export interface Profile {
  id: string
  instagram_handle: string
  instagram_url: string | null
  display_name: string | null
  bio_text: string | null
  profile_photo_url: string | null
  follower_count: number | null
  following_count: number | null
  post_count: number | null
  location_text: string | null
  is_discoverable: boolean
  opted_in_at: string
  opted_out_at: string | null
  last_crawled_at: string | null
  next_crawl_at: string | null
  crawl_status: 'pending' | 'crawling' | 'complete' | 'error'
  created_at: string
  updated_at: string
}

export interface ProfileAnalysis {
  id: string
  profile_id: string
  personality_summary: string | null
  writing_style: string | null
  emotional_register: string | null
  humor_type: string | null
  topics_corpus: string[] | null
  hashtag_clusters: Record<string, number> | null
  geo_clusters: GeoCluster[] | null
  primary_city: string | null
  neighborhoods: string[] | null
  aesthetic_tags: string[] | null
  color_palette: string | null
  post_frequency: string | null
  active_hours: string | null
  content_type_ratio: Record<string, number> | null
  model_version: string
  processed_at: string
}

export interface GeoCluster {
  area: string
  city: string
  count: number
}

export interface Post {
  id: string
  profile_id: string
  instagram_post_id: string
  caption: string | null
  hashtags: string[] | null
  tagged_location: string | null
  tagged_lat: number | null
  tagged_lng: number | null
  post_type: 'photo' | 'reel' | 'carousel' | null
  thumbnail_url: string | null
  like_count: number | null
  comment_count: number | null
  posted_at: string | null
  created_at: string
}

export interface Unlock {
  id: string
  seeker_id: string
  profile_id: string
  vibe_check: VibeCheckOutput | null
  sparks: string[] | null
  credits_spent: number
  created_at: string
}

export interface Match {
  id: string
  seeker_id: string
  profile_id: string
  seeker_status: 'saved' | 'messaging' | 'met' | 'passed'
  match_brief: string | null
  is_mutual: boolean
  brief_sent_at: string | null
  date_nudge_sent_at: string | null
  date_nudge_venue: string | null
  met_irl: boolean
  created_at: string
  updated_at: string
}

export interface WingmanSession {
  id: string
  match_id: string
  message_count: number
  last_context: string | null
  suggestions: string[] | null
  created_at: string
  updated_at: string
}

// Agent output types
export interface VibeCheckOutput {
  aesthetic: string
  personality: string
  lifestyle: string
  interests: string[]
  sparks: [string, string, string]
}

export interface SearchResult {
  profile_id: string
  instagram_handle: string
  display_name: string | null
  profile_photo_url: string | null
  similarity: number
  personality_summary: string | null
  aesthetic_tags: string[] | null
  geo_clusters: GeoCluster[] | null
  primary_city: string | null
  ai_summary: string // generated by Search Agent
}

// Telegram session state
export interface SessionData {
  step: 'idle' | 'searching' | 'viewing_results' | 'wingman' | 'onboarding'
  searchQuery?: string
  searchResults?: SearchResult[]
  resultIndex?: number
  activeMatchId?: string
  activeProfileId?: string
  onboardingStep?: number
}
